development:
  host: "localhost"
  port: 5432
  database: "ecommerce_dw"
  username: "data_engineer"
  password: "secure_password"
  
production:
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  database: "${DB_NAME}"
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"

aws_rds:
  host: "${AWS_RDS_HOST}"
  port: 5432
  database: "${AWS_RDS_DB}"
  username: "${AWS_RDS_USER}"
  password: "${AWS_RDS_PASSWORD}"

connection_pool:
  min_connections: 5
  max_connections: 20
  retry_attempts: 3
  timeout: 30 